'use strict';

const fs = require('fs');
const path = require('path');
const utils = require('./utils');
const sanitize = require('./sanitize');
const classifier = require('./classifier');

// Group tasks (which already carry a localDate from message timestamps)
// into per-day journal files, then write all derived data files.

function buildJournal(tasks, cfg) {
  const byDate = new Map();
  for (const t of tasks) {
    if (!t.date) continue;
    if (!byDate.has(t.date)) byDate.set(t.date, []);
    byDate.get(t.date).push(t);
  }
  const written = [];
  for (const [date, list] of byDate.entries()) {
    list.sort((a, b) => {
      const at = a.firstTimestamp ? new Date(a.firstTimestamp).getTime() : 0;
      const bt = b.firstTimestamp ? new Date(b.firstTimestamp).getTime() : 0;
      return at - bt;
    });
    const file = path.join(cfg.journalDir, date + '.md');
    const md = renderDay(date, list, cfg);
    utils.writeTextSafe(file, md);
    written.push(file);
  }
  return written;
}

function renderDay(date, tasks, cfg) {
  const lines = [];
  lines.push('# ' + date);
  lines.push('');
  lines.push('> ' + tasks.length + ' task(s) on this day. Generated by CodexJournal-Lite.');
  lines.push('');
  for (const t of tasks) {
    const time = t.time || '??:??';
    const title = sanitize.redactText(t.title || '(untitled)');
    lines.push('## ' + time + ' · ' + title);
    lines.push('');
    lines.push('- type: `' + (t.taskType || 'general') + '`');
    if (t.keywords && t.keywords.length) {
      lines.push('- keywords: ' + t.keywords.map((k) => '`' + k + '`').join(', '));
    }
    if (t.projectPath) {
      lines.push('- project: `' + sanitize.redactPath(t.projectPath) + '`');
    }
    lines.push('- source: `' + t.source + '`');
    lines.push('- messages: ' + t.messageCount);
    lines.push('- raw: `' + sanitize.redactPath(t.rawFilePath) + '`');
    lines.push('');
    if (t.userSummary) {
      lines.push('### User');
      lines.push('');
      lines.push(sanitize.redactText(t.userSummary));
      lines.push('');
    }
    if (t.assistantSummary) {
      lines.push('### Assistant');
      lines.push('');
      lines.push(sanitize.redactText(t.assistantSummary));
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }
  return lines.join('\n');
}

function buildStats(tasks, cfg) {
  const stats = {
    generatedAt: new Date().toISOString(),
    totals: {
      tasks: tasks.length,
      messages: 0,
      days: 0,
      unknownTasks: 0
    },
    bySource: {},
    byType: {},
    byDay: {},
    topKeywords: {}
  };
  const daySet = new Set();
  for (const t of tasks) {
    stats.totals.messages += t.messageCount || 0;
    if (t.date) daySet.add(t.date);
    if (t.taskType === 'unknown') stats.totals.unknownTasks += 1;
    stats.bySource[t.source || 'unknown'] = (stats.bySource[t.source || 'unknown'] || 0) + 1;
    stats.byType[t.taskType || 'general'] = (stats.byType[t.taskType || 'general'] || 0) + 1;
    if (t.date) stats.byDay[t.date] = (stats.byDay[t.date] || 0) + 1;
    for (const k of t.keywords || []) {
      stats.topKeywords[k] = (stats.topKeywords[k] || 0) + 1;
    }
  }
  stats.totals.days = daySet.size;
  // Sort byDay by date asc, and top keywords desc.
  const sortedByDay = Object.entries(stats.byDay).sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0);
  stats.byDay = Object.fromEntries(sortedByDay);
  const sortedKw = Object.entries(stats.topKeywords)
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .slice(0, 50);
  stats.topKeywords = Object.fromEntries(sortedKw);
  return stats;
}

function buildSearch(tasks, cfg) {
  const lines = [];
  lines.push('# CodexJournal-Lite Search Index');
  lines.push('');
  lines.push('> Auto-generated. All entries are redacted. Safe to grep / full-text search.');
  lines.push('');
  lines.push('| date | time | type | title | keywords | source | raw |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- |');
  const sorted = tasks.slice().sort((a, b) => {
    const ad = (a.date || '') + 'T' + (a.time || '00:00');
    const bd = (b.date || '') + 'T' + (b.time || '00:00');
    return ad < bd ? 1 : ad > bd ? -1 : 0;
  });
  for (const t of sorted) {
    const title = sanitize.redactText((t.title || '').replace(/\|/g, '\\|'));
    const kws = (t.keywords || []).slice(0, 8).map((k) => '`' + k + '`').join(' ');
    const src = (t.source || '').replace(/\|/g, '\\|');
    const raw = sanitize.redactPath(t.rawFilePath || '').replace(/\|/g, '\\|');
    lines.push('| ' + (t.date || 'unknown') + ' | ' + (t.time || '??:??') + ' | `' + (t.taskType || 'general') + '` | ' + title + ' | ' + kws + ' | ' + src + ' | ' + raw + ' |');
  }
  lines.push('');
  // Verbose section for full-text search.
  lines.push('## Details');
  lines.push('');
  for (const t of sorted) {
    const title = sanitize.redactText(t.title || '(untitled)');
    lines.push('### ' + (t.date || 'unknown') + ' ' + (t.time || '??:??') + ' · ' + title);
    lines.push('');
    lines.push('- id: `' + t.id + '`');
    lines.push('- type: `' + (t.taskType || 'general') + '`');
    if (t.keywords && t.keywords.length) {
      lines.push('- keywords: ' + t.keywords.map((k) => '`' + k + '`').join(', '));
    }
    if (t.projectPath) lines.push('- project: `' + sanitize.redactPath(t.projectPath) + '`');
    lines.push('- source: `' + t.source + '`');
    lines.push('- raw: `' + sanitize.redactPath(t.rawFilePath) + '`');
    if (t.userSummary) {
      lines.push('');
      lines.push('User: ' + sanitize.redactText(t.userSummary));
    }
    if (t.assistantSummary) {
      lines.push('');
      lines.push('Assistant: ' + sanitize.redactText(t.assistantSummary));
    }
    lines.push('');
  }
  return lines.join('\n');
}

function readProjectVersion(projectRoot) {
  // Pull the version straight from package.json so the README cannot
  // drift away from the version in `npm run verify`.
  try {
    const fs = require('fs');
    const path = require('path');
    const raw = fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8');
    const pkg = JSON.parse(raw);
    return pkg && typeof pkg.version === 'string' ? pkg.version : 'unknown';
  } catch (_) {
    return 'unknown';
  }
}

function buildDashboard(tasks, stats, cfg) {
  const recent = tasks.slice().sort((a, b) => {
    const ad = (a.date || '') + 'T' + (a.time || '00:00');
    const bd = (b.date || '') + 'T' + (b.time || '00:00');
    return ad < bd ? 1 : ad > bd ? -1 : 0;
  }).slice(0, 15);

  const version = readProjectVersion(cfg && cfg.projectRoot);

  const lines = [];
  lines.push('# CodexJournal-Lite Dashboard');
  lines.push('');
  lines.push('Local-only personal AI work journal built from Codex session files. **No data leaves this machine.**');
  lines.push('');
  lines.push('## Version');
  lines.push('');
  lines.push('`' + version + '` (this local dashboard is regenerated on every `npm run archive` from `package.json`).');
  lines.push('');
  lines.push('## Dashboard');
  lines.push('');
  lines.push('| metric | value |');
  lines.push('| --- | --- |');
  lines.push('| total tasks | ' + stats.totals.tasks + ' |');
  lines.push('| total messages | ' + stats.totals.messages + ' |');
  lines.push('| active days | ' + stats.totals.days + ' |');
  lines.push('| unknown tasks | ' + stats.totals.unknownTasks + ' |');
  lines.push('');
  lines.push('### Sources');
  lines.push('');
  lines.push('| source | count |');
  lines.push('| --- | --- |');
  const sources = Object.entries(stats.bySource).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  for (const [k, v] of sources) lines.push('| `' + k + '` | ' + v + ' |');
  lines.push('');
  lines.push('### Task types');
  lines.push('');
  lines.push('| type | count |');
  lines.push('| --- | --- |');
  const types = Object.entries(stats.byType).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  for (const [k, v] of types) lines.push('| `' + k + '` | ' + v + ' |');
  lines.push('');
  lines.push('### Top keywords');
  lines.push('');
  lines.push('| keyword | count |');
  lines.push('| --- | --- |');
  const kws = Object.entries(stats.topKeywords).slice(0, 30);
  for (const [k, v] of kws) lines.push('| `' + k + '` | ' + v + ' |');
  lines.push('');
  lines.push('### Recent tasks');
  lines.push('');
  for (const t of recent) {
    const title = sanitize.redactText(t.title || '(untitled)');
    lines.push('- ' + (t.date || 'unknown') + ' ' + (t.time || '??:??') + ' · `' + (t.taskType || 'general') + '` · ' + title);
  }
  lines.push('');
  lines.push('## Privacy');
  lines.push('');
  lines.push('- 100% local. No network calls. No telemetry. No upload.');
  lines.push('- All archive outputs (`journal/`, `data/tasks.json`, `data/search.md`, `reports/dashboard.md`) are passed through `src/sanitize.js` before being written.');
  lines.push('- Redacted: OpenAI-style API keys, environment variable assignments (OpenAI / Anthropic / Gemini / Azure), authorization header values, cookie / session identifiers (`connect.sid`), GitHub / Slack tokens, and the local Windows username in any path (`C:\\Users\\<USER>\\` -> `C:\\Users\\<USER>\\`).');
  lines.push('- `data/index.json` is a local-only cache (gitignored) and keeps the original absolute paths of the session files as keys so that incremental fingerprint lookups stay stable across runs. The embedded per-task `rawFilePath`, `userSummary`, and `assistantSummary` fields in that file ARE still passed through sanitize.');
  lines.push('- Original `.codex/sessions` files are NEVER modified or deleted.');
  lines.push('');
  return lines.join('\n');
}

function buildIndexFile(index, cfg) {
  return {
    generatedAt: new Date().toISOString(),
    sessionsDir: cfg.sessionsDir,
    files: index.files || {}
  };
}

module.exports = {
  buildJournal,
  buildStats,
  buildSearch,
  buildDashboard,
  buildReadme: buildDashboard,
  buildIndexFile
};
